Controllers/CashierPOSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Uling_RestaurantManagementSystem.Models.SQL;
using Uling_RestaurantManagementSystem.Models.Custom;

namespace Uling_RestaurantManagementSystem.Controllers
{
    public class CashierPOSController : Controller
    {
        private readonly db_urmsEntities db = new db_urmsEntities();

        private bool IsUserAuthorized(int userType)
        {
            if (userType != 2)
            {
                return false;
            }
            else
            {
                return true;
            }
        }

        private ActionResult NotAuthorized(int userType)
        {
            string actionName = "";
            string controllerName = "";

            /*
                User Types

                1 ---> Manager
                2 ---> Cashier
                3 ---> Cook
            */

            switch (userType)
            {
                case 1:
                    actionName = "LoadManagerDashboard";
                    controllerName = "ManagerDashboard";
                    break;
                case 3:
                    actionName = "LoadCookDashboard";
                    controllerName = "CookDashboard";
                    break;
                default:
                    actionName = "SignIn";
                    controllerName = "Main";
                    break;
            }
            return RedirectToAction(actionName, controllerName);
        }

        [HttpGet]
        public ActionResult LoadCashierPOS()
        {
            // Check if the user is authorized.
            var userType = Convert.ToInt32(Session["user_type"]);
            if (!IsUserAuthorized(userType)) { return NotAuthorized(userType); }

            IEnumerable<tbl_menu_items> menuItems = db.tbl_menu_items.ToList();
            IEnumerable<tbl_discounts> discounts = db.tbl_discounts.Where(d => d.is_active == 1).ToList();

            CashierPOSViewModel cashierPOSViewModel = new CashierPOSViewModel
            {
                MenuItems = menuItems,
                Discounts = discounts
            };

            ViewBag.CurrentPage = "cashier__pos";
            return View(cashierPOSViewModel);
        }

        [HttpPost]
        public JsonResult AddToCart(int menu_item_id, int quantity)
        {
            var existingOrderItems = Session["OrderItems"] as List<OrderItemModel> ?? new List<OrderItemModel>();
            tbl_menu_items menuItem = db.tbl_menu_items.Find(menu_item_id);

            if (menuItem == null)
            {
                return Json(new { success = false, message = "Menu item not found" });
            }

            int nextOrderItemId = 0;
            if (existingOrderItems.Count() > 0) {
                List<int> orderItemIdArr = new List<int>();
                foreach (var item in existingOrderItems)
                {
                    orderItemIdArr.Add(item.OrderItemId);
                }
                var maxOrderItem = orderItemIdArr.OrderByDescending(oi => oi).First();
                nextOrderItemId = Convert.ToInt32(maxOrderItem) + 1;
            }
            else
            {
                nextOrderItemId = 1;
            }

            OrderItemModel orderItemModel = new OrderItemModel
            {
                OrderItemId = nextOrderItemId,
                OrderId = 0,
                MenuItemId = menu_item_id,
                MenuName = menuItem.name,
                Unit_Price = menuItem.price,
                Quantity = quantity,
                DiscountId = 0,
                LineTotal = Convert.ToDecimal(menuItem.price) * quantity
            };

            existingOrderItems.Add(orderItemModel);

            Session["OrderItems"] = existingOrderItems;
            return Json(new { success = true, orderItemModel });
        }

        [HttpPost]
        public ActionResult ApplyDiscount(int discount_id, int order_item_id)
        {
            var existingOrderItems = Session["OrderItems"] as List<OrderItemModel> ?? new List<OrderItemModel>();
            foreach (var item in existingOrderItems)
            {
                if (item.OrderItemId == order_item_id)
                {
                    item.DiscountId = discount_id;
                }
            }

            Session["OrderItems"] = existingOrderItems;
            return Json(new { success = true, message = "Discount applied successfully" });
        }

        [HttpPost]
        public JsonResult RemoveToCart(int menu_item_id)
        {
            var existingOrderItems = Session["OrderItems"] as List<OrderItemModel> ?? new List<OrderItemModel>();

            // Collect items to remove
            var itemsToRemove = new List<OrderItemModel>();

            foreach (var item in existingOrderItems)
            {
                if (item.MenuItemId == menu_item_id)
                {
                    itemsToRemove.Add(item);
                }
            }

            // Remove collected items
            foreach (var item in itemsToRemove)
            {
                existingOrderItems.Remove(item);
            }

            Session["OrderItems"] = existingOrderItems;
            return Json(new { success = true });
        }

        [HttpPost]
        public ActionResult PlaceOrder(string customer_name = null, string contact_number = null, string email = null)
        {
            var existingOrderItems = Session["OrderItems"] as List<OrderItemModel> ?? new List<OrderItemModel>();

            if (existingOrderItems == null || existingOrderItems.Count == 0)
            {
                return HttpNotFound();
            }

            // check request parameters
            string customerName = !string.IsNullOrEmpty(customer_name) ? customer_name : "-";
            string contactNumber = !string.IsNullOrEmpty(contact_number) ? contact_number : "-";
            string emailAddress = !string.IsNullOrEmpty(email) ? email : "-";

            DateTime today = DateTime.Now;
            tbl_orders newOrder = new tbl_orders
            {
                order_type = "Counter",
                customer_name = customerName,
                contact_number = contactNumber,
                email = emailAddress,
                date_ordered = today,
                order_status = "Accepted"
            };

            db.tbl_orders.Add(newOrder);

            decimal orderTotalAmount = 0;

            // re-populate the order items using the main context (tbl_order_items) / model
            List<tbl_order_items> orderItems = new List<tbl_order_items>();

            // Create a list for receipt items
            List<ReceiptItemModel> receiptItemArray = new List<ReceiptItemModel>();

            foreach (var item in existingOrderItems)
            {
                tbl_discounts discount = db.tbl_discounts.Where(d => d.discount_id == item.DiscountId).FirstOrDefault();
                decimal initialLinePrice = item.LineTotal;
                decimal finalLinePrice = 0;

                tbl_order_items newOrderItem = new tbl_order_items
                {
                    order_id = newOrder.order_id,
                    menu_item_id = item.MenuItemId,
                    quantity = item.Quantity
                };

                if (discount != null && item.DiscountId != 0)
                {
                    // check for discounts
                    if (discount.discount_percentage != 0 && discount.discount_amount == 0)
                    {
                        // has discount percentage off
                        decimal discountDecimalForm = discount.discount_percentage / 100;
                        decimal discountOff = item.Unit_Price * discountDecimalForm;
                        finalLinePrice = initialLinePrice - discountOff;
                    }
                    else if (discount.discount_percentage == 0 && discount.discount_amount != 0)
                    {
                        // has discount fix amount off
                        finalLinePrice = initialLinePrice - discount.discount_amount;
                    }

                    newOrderItem.discount_id = item.DiscountId;
                }
                else {
                    // no discount
                    finalLinePrice = initialLinePrice;
                }

                newOrderItem.line_price = finalLinePrice;
                
                orderItems.Add(newOrderItem);
                orderTotalAmount += finalLinePrice;

                // insert the order item to the receipt items array
                ReceiptItemModel receiptItemModel = new ReceiptItemModel
                {
                    Item = item.MenuName,
                    Quantity = item.Quantity,
                    Unit_Price = item.Unit_Price,
                    Total_Price = finalLinePrice
                };

                receiptItemArray.Add(receiptItemModel);
            }

            // loop over the order items (orderItems) and save each item to db
            orderItems.ForEach(oi => db.tbl_order_items.Add(oi));

            // update the order total_amount
            newOrder.total_amount = orderTotalAmount;

            int userId = Convert.ToInt32(Session["user_id"] ?? 0);

            // save receipt record
            tbl_receipts receipt = new tbl_receipts
            {
                order_id = newOrder.order_id,
                receipt_date = DateTime.Now,
                sub_total = newOrder.total_amount,
                amount_due = newOrder.total_amount,
                cashier_id = userId
            };

            db.tbl_receipts.Add(receipt);

            db.SaveChanges();

            Session.Remove("OrderItems");

            tbl_users cashier = db.tbl_users.Where(u => u.user_id == userId).FirstOrDefault();

            if (cashier == null) {
                return HttpNotFound();
            }

            return Json(new { 

Controllers/ManagerAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
// imports
using Uling_RestaurantManagementSystem.Models.SQL;

namespace Uling_RestaurantManagementSystem.Controllers
{
    public class ManagerAccountsController : Controller
    {
        private db_urmsEntities db = new db_urmsEntities();

        private bool IsUserAuthorized(int userType)
        {
            if (userType != 1)
            {
                return false;
            }
            else
            {
                return true;
            }
        }

        private ActionResult NotAuthorized(int userType)
        {
            string actionName = "";
            string controllerName = "";

            /*
                User Types

                1 ---> Manager
                2 ---> Cashier
                3 ---> Cook
            */

            switch (userType)
            {
                case 2:
                    actionName = "LoadCashierDashboard";
                    controllerName = "CashierDashboard";
                    break;
                case 3:
                    actionName = "LoadCookDashboard";
                    controllerName = "CookDashboard";
                    break;
                default:
                    actionName = "SignIn";
                    controllerName = "Main";
                    break;
            }
            return RedirectToAction(actionName, controllerName);
        }

        [HttpGet]
        public ActionResult LoadManagerAccounts()
        {
            // Check if the user is authorized.
            var userType = Convert.ToInt32(Session["user_type"]);
            if (!IsUserAuthorized(userType)) { return NotAuthorized(userType); }

            List<tbl_users> users = db.tbl_users
                .Where(u =>
                    u.usertype == 2 ||
                    u.usertype == 3
                )
                .ToList();

            ViewBag.CurrentPage = "manager__accounts";
            return View(users);
        }

        [HttpPost]
        public ActionResult AddAccount(string firstname, string middlename, string lastname, int usertype, string email, string password)
        {
            tbl_users user = new tbl_users
            {
                firstname = firstname,
                middlename = middlename,
                lastname = lastname,
                usertype = usertype,
                email = email,
                password = password
            };

            db.tbl_users.Add(user);
            db.SaveChanges();

            return Json(new { success = true, message = "New account has ben added successfully" });
        }

        [HttpGet]
        public ActionResult ViewAccountDetails(int user_id)
        {
            // Check if the user is authorized.
            var userType = Convert.ToInt32(Session["user_type"]);
            if (!IsUserAuthorized(userType)) { return NotAuthorized(userType); }

            tbl_users user = db.tbl_users.Find(user_id);

            ViewBag.CurrentPage = "manager__accounts";
            return View(user);
        }

        [HttpGet]
        public ActionResult LoadEditAccount(int user_id)
        {
            // Check if the user is authorized.
            var userType = Convert.ToInt32(Session["user_type"]);
            if (!IsUserAuthorized(userType)) { return NotAuthorized(userType); }

            tbl_users user = db.tbl_users.Find(user_id);

            ViewBag.CurrentPage = "manager__accounts";
            return View(user);
        }

        [HttpPost]
        public ActionResult UpdateAccount(int user_id, string firstname, string middlename, string lastname, int usertype, string email, string password) 
        {
            tbl_users user = db.tbl_users.Find(user_id);
            
            if(user == null)
            {
                return HttpNotFound();
            }

            user.firstname = firstname;
            user.middlename = middlename;
            user.lastname = lastname;
            user.usertype = usertype;
            user.email = email;
            user.password = password;
            db.SaveChanges();

            return Json(new { success = true, message = "Account details has been updated successfully" });
        }

        [HttpPost]
        public ActionResult DeleteAccount(int user_id)
        {
            tbl_users user = db.tbl_users
                .Where(u => u.user_id == user_id)
                .FirstOrDefault();

            if (user == null)
            {
                return HttpNotFound();
            }

            db.tbl_users.Remove(user);
            db.SaveChanges();

            return Json(new { success = true, message = "Account has been deleted successfully" });
        }
    }
}

Controllers/ManagerMenuItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Uling_RestaurantManagementSystem.Models.SQL;

namespace Uling_RestaurantManagementSystem.Controllers
{
    public class ManagerMenuItemsController : Controller
    {
        private readonly db_urmsEntities db = new db_urmsEntities();

        private bool IsUserAuthorized(int userType)
        {
            if (userType != 1)
            {
                return false;
            }
            else
            {
                return true;
            }
        }

        private ActionResult NotAuthorized(int userType)
        {
            string actionName = "";
            string controllerName = "";

            /*
                User Types

                1 ---> Manager
                2 ---> Cashier
                3 ---> Cook
            */

            switch (userType)
            {
                case 2:
                    actionName = "LoadCashierDashboard";
                    controllerName = "CashierDashboard";
                    break;
                case 3:
                    actionName = "LoadCookDashboard";
                    controllerName = "CookDashboard";
                    break;
                default:
                    actionName = "SignIn";
                    controllerName = "Main";
                    break;
            }
            return RedirectToAction(actionName, controllerName);
        }

        public ActionResult LoadManagerMenuItems()
        {
            // Check if the user is authorized.
            var userType = Convert.ToInt32(Session["user_type"]);
            if (!IsUserAuthorized(userType)) { return NotAuthorized(userType); }

            List<tbl_menu_items> menuItems = db.tbl_menu_items.ToList();

            ViewBag.CurrentPage = "manager__menu_items";
            return View(menuItems);
        }

        [HttpPost]
        public ActionResult UpdateMenuItemStatus(int menu_item_id, int is_available)
        {
            tbl_menu_items menuItem = db.tbl_menu_items.Find(menu_item_id);

            bool isAvailable = false;
            if(is_available == 1)
            {
                isAvailable = true;
            }

            menuItem.is_available = isAvailable;

            db.SaveChanges();

            return Json(new { success = true, message = "Menu item status has been changed successfully." });
        }
    }
}

Views/Shared/_Sidebar.cshtml
@using Uling_RestaurantManagementSystem.Models.SQL

@{ 
    int pendingCounterOrdersCount = 0;
    int pendingReservationOrdersCount = 0;
    int pendingTakeOutOrdersCount = 0;
}

@{
    if (Session["user_type"] != null)
    {
        var userType = Convert.ToInt32(Session["user_type"]);

        if (userType == 3)
        {
            // Create an instance of the database context
            using (var db = new db_urmsEntities())
            {
                pendingCounterOrdersCount = db.tbl_orders
                    .Count(o =>
                        !o.tbl_payment.Any() &&
                        !o.tbl_reservations.Any() &&
                        o.order_type == "Counter" &&
                        o.order_status == "Accepted"
                    );

                pendingReservationOrdersCount = db.tbl_orders
                    .Count(o =>
                        o.tbl_reservations.Any() &&
                        o.tbl_payment.Any() &&
                        // status (only fetch the reservations that is already verified and paid)
                        o.order_status == "Accepted" &&
                        o.tbl_reservations.FirstOrDefault().reservation_status == "Accepted" &&
                        o.tbl_payment.FirstOrDefault().payment_status == "Accepted" &&
                        // fetch orders that type is Online and payment method is not CASH
                        o.order_type == "Online" &&
                        o.tbl_payment.FirstOrDefault().payment_method != "Cash"
                    );

                pendingTakeOutOrdersCount = db.tbl_orders
                   .Count(o =>
                    o.tbl_payment.Any() &&
                    !o.tbl_reservations.Any() &&
                    // status (only fetch the take-out orders that is already accepted and paid)
                    o.order_status == "Accepted" &&
                    o.tbl_payment.FirstOrDefault().payment_status == "Accepted" &&
                    // fetch orders that type is Online and payment method is not CASH
                    o.order_type == "Online" &&
                    o.tbl_payment.FirstOrDefault().payment_method != "Cash"
                   );
            }
        }
    }
}

@{
    var portalIcon = "";
    var portalText = "";

    if (Session["user_type"] != null)
    {
        var userType = Convert.ToInt32(Session["user_type"]);

        switch (userType)
        {
            case 1: // ---> Manager
                portalIcon = "fa-user-tie";
                portalText = "Manager";
                break;
            case 2: // ---> Cashier
                portalIcon = "fa-user-alt";
                portalText = "Cashier";
                break;
            case 3: // ---> Cook
                portalIcon = "fa-user-alt";
                portalText = "Cook";
                break;
            default:
                break;
        }
    }
}


<div class="border-end bg-white" id="sidebar-wrapper">
    <div class="sidebar-heading">
        <h5 class="font-weight-600 text-center mt-2"><span class="text-theme-1">Uling</span> Top View Restaurant</h5>
        <div class="text-center mt-sm-3">
            <i class="fas @portalIcon text-secondary"></i> <small class="text-dark">@portalText</small>
        </div>
    </div>
    <div class="list-group list-group-flush mt-sm-5 pt-sm-3">
        @if (Session["user_id"] != null && Session["user_type"] != null)
        {
            int userType = Convert.ToInt32(Session["user_type"]);
            if (userType == 1)
            {
                @* Manager Menu *@
                <a class="list-group-item list-group-item-action list-group-item-light border-top p-3
                    @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "manager__dashboard" ? "active_item" : "")"
                   href="@Url.Action("LoadManagerDashboard", "ManagerDashboard")">
                    <i class="fas fa-chart-line @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "manager__dashboard" ? "active-item-icon" : "")"></i>
                    <span class="ms-2 @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "manager__dashboard" ? "active-item-text" : "")">Dashboard</span>
                </a>

                <a class="list-group-item list-group-item-action list-group-item-light border-top p-3
                    @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "manager__reservations" ? "active_item" : "")"
                   href="@Url.Action("LoadManagerReservation", "ManagerReservations")">
                    <i class="fas fa-calendar-check @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "manager__reservations" ? "active-item-icon" : "")"></i>
                    <span class="ms-2 @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "manager__reservations" ? "active-item-text" : "")">Reservations</span>
                </a>

                <a class="list-group-item list-group-item-action list-group-item-light border-top p-3
                    @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "manager__takeout_orders" ? "active_item" : "")"
                   href="@Url.Action("LoadTakeOutOrders", "ManagerTakeOutOrders")">
                    <i class="fas fa-shopping-bag @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "manager__takeout_orders" ? "active-item-icon" : "")"></i>
                    <span class="ms-2 @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "manager__takeout_orders" ? "active-item-text" : "")">Take-Out Orders</span>
                </a>

                <a class="list-group-item list-group-item-action list-group-item-light border-top p-3
                    @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "manager__counter_orders" ? "active_item" : "")"
                   href="@Url.Action("LoadManagerCounterOrders", "ManagerCounterOrders")">
                    <i class="fas fa-tasks @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "manager__counter_orders" ? "active-item-icon" : "")"></i>
                    <span class="ms-2 @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "manager__counter_orders" ? "active-item-text" : "")">Walk-In Orders</span>
                </a>

                <a class="list-group-item list-group-item-action list-group-item-light border-top p-3
                    @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "manager__menu_items" ? "active_item" : "")"
                   href="@Url.Action("LoadManagerMenuItems", "ManagerMenuItems")">
                    <i class="fas fa-utensils @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "manager__menu_items" ? "active-item-icon" : "")"></i>
                    <span class="ms-2 @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "manager__menu_items" ? "active-item-text" : "")">Menu Items</span>
                </a>

                <a class="list-group-item list-group-item-action list-group-item-light border-top p-3
                    @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "manager__accounts" ? "active_item" : "")"
                   href="@Url.Action("LoadManagerAccounts", "ManagerAccounts")">
                    <i class="fas fa-users @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "manager__accounts" ? "active-item-icon" : "")"></i>
                    <span class="ms-2 @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "manager__accounts" ? "active-item-text" : "")">Accounts</span>
                </a>
            }
            else if (userType == 2)
            {
                @* Cashier Menu *@
                <a class="list-group-item list-group-item-action list-group-item-light border-top p-3
                    @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cashier__dashboard" ? "active_item" : "")"
                   href="@Url.Action("LoadCashierDashboard", "CashierDashboard")">
                    <i class="fas fa-chart-line @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cashier__dashboard" ? "active-item-icon" : "")"></i>
                    <span class="ms-2 @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cashier__dashboard" ? "active-item-text" : "")">Dashboard</span>
                </a>

                <a class="list-group-item list-group-item-action list-group-item-light border-top p-3
                    @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cashier__orders" ? "active_item" : "")"
                   href="@Url.Action("LoadCashierOrders", "CashierOrders")">
                    <i class="fas fa-shopping-cart @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cashier__orders" ? "active-item-icon" : "")"></i>
                    <span class="ms-2 @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cashier__orders" ? "active-item-text" : "")">Orders</span>
                </a>


                <a class="list-group-item list-group-item-action list-group-item-light border-top p-3
                    @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cashier__pos" ? "active_item" : "")"
                   href="@Url.Action("LoadCashierPOS", "CashierPOS")">
                    <i class="fas fa-tasks @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cashier__pos" ? "active-item-icon" : "")"></i>
                    <span class="ms-2 @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cashier__pos" ? "active-item-text" : "")">POS</span>
                </a>
            }
            else if (userType == 3)
            {
                @* Cook Menu *@
                <a class="list-group-item list-group-item-action list-group-item-light border-top p-3
                    @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cook__dashboard" ? "active_item" : "")"
                   href="@Url.Action("LoadCookDashboard", "CookDashboard")">
                    <i class="fas fa-chart-line @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cook__dashboard" ? "active-item-icon" : "")"></i>
                    <span class="ms-2 @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cook__dashboard" ? "active-item-text" : "")">Dashboard</span>
                </a>

                <a class="list-group-item list-group-item-action list-group-item-light border-top p-3
                    @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cook__counter_orders" ? "active_item" : "")"
                   href="@Url.Action("LoadCookCounterOrders", "CookCounterOrders")">
                    <i class="fas fa-tasks @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cook__counter_orders" ? "active-item-icon" : "")"></i>
                    <span class="ms-2 @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cook__counter_orders" ? "active-item-text" : "")">Counter Orders</span>
                    <span class="badge bg-danger float-end">@pendingCounterOrdersCount</span>
                </a>

                <a class="list-group-item list-group-item-action list-group-item-light border-top p-3
                    @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cook__reservation_orders" ? "active_item" : "")"
                   href="@Url.Action("LoadCookReservationOrders", "CookReservationOrders")">
                    <i class="fas fa-calendar-check @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cook__reservation_orders" ? "active-item-icon" : "")"></i>
                    <span class="ms-2 @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cook__reservation_orders" ? "active-item-text" : "")">Reservation Orders</span>
                    <span class="badge bg-danger float-end">@pendingReservationOrdersCount</span>
                </a>

                <a class="list-group-item list-group-item-action list-group-item-light border-top p-3
                    @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cook__takeout_orders" ? "active_item" : "")"
                   href="@Url.Action("LoadCookTakeOutOrders", "CookTakeOutOrders")">
                    <i class="fas fa-shopping-bag @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cook__takeout_orders" ? "active-item-icon" : "")"></i>
                    <span class="ms-2 @(ViewBag.CurrentPage != null && ViewBag.CurrentPage == "cook__takeout_orders" ? "active-item-text" : "")">Take-Out Orders</span>
                    <span class="badge bg-danger float-end">@pendingTakeOutOrdersCount</span>
                </a>
            }
        }

        <a class="list-group-item list-group-item-action list-group-item-light border-bottom p-3"
           href="/SupervisorAttendance/AttendanceList"
           data-bs-toggle="modal" data-bs-target="#logoutConfirmationModal">
            <i class="fas fa-sign-out-alt text-secondary"></i>
            <span class="ms-2 text-secondary">Logout</span>
        </a>
    </div>
</div>

<!-- Sign Out Modal -->
<div class="modal fade" id="logoutConfirmationModal" tabindex="-1" aria-labelledby="logoutConfirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            @using (Html.BeginForm("SignOut", "Main", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Confirm Sign Out</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to sign out?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn-urms btn-theme-1 px-4">Yes</button>
                </div>
            }
        </div>
    </div>
</div>