Controllers/ManagerCounterOrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Uling_RestaurantManagementSystem.Models.Custom;
using Uling_RestaurantManagementSystem.Models.SQL;

namespace Uling_RestaurantManagementSystem.Controllers
{
    public class ManagerCounterOrdersController : Controller
    {
        private readonly db_urmsEntities db = new db_urmsEntities();

        private bool IsUserAuthorized(int userType)
        {
            if (userType != 1)
            {
                return false;
            }
            else
            {
                return true;
            }
        }

        private ActionResult NotAuthorized(int userType)
        {
            string actionName = "";
            string controllerName = "";

            /*
                User Types

                1 ---> Manager
                2 ---> Cashier
                3 ---> Cook
            */

            switch (userType)
            {
                case 2:
                    actionName = "LoadCashierDashboard";
                    controllerName = "CashierDashboard";
                    break;
                case 3:
                    actionName = "LoadCookDashboard";
                    controllerName = "CookDashboard";
                    break;
                default:
                    actionName = "SignIn";
                    controllerName = "Main";
                    break;
            }
            return RedirectToAction(actionName, controllerName);
        }

        public ActionResult LoadManagerCounterOrders()
        {
            // Check if the user is authorized.
            var userType = Convert.ToInt32(Session["user_type"]);
            if (!IsUserAuthorized(userType)) { return NotAuthorized(userType); }

            List<tbl_orders> orders = db.tbl_orders
                .Where(o =>
                    // fetch orders that doesn't have any corresponding payment and reservation record
                    !o.tbl_payment.Any() &&
                    !o.tbl_reservations.Any() &&
                    // get counter order type orders only
                    o.order_type == "Counter"
                )
                .ToList();

            ViewBag.CurrentPage = "manager__counter_orders";
            return View(orders);
        }

        public ActionResult ViewOrderDetails(int order_id)
        {
            // Check if the user is authorized.
            var userType = Convert.ToInt32(Session["user_type"]);
            if (!IsUserAuthorized(userType)) { return NotAuthorized(userType); }

            tbl_orders order = db.tbl_orders.Find(order_id);

            if (order == null)
            {
                return HttpNotFound();
            }

            List<tbl_order_items> orderItems = db.tbl_order_items
                .Where(oi => oi.order_id == order_id)
                .ToList();

            PlaceOrderModel placeOrderModel = new PlaceOrderModel
            {
                Order = order,
                OrderItems = orderItems
            };


            ViewBag.CurrentPage = "manager__counter_orders";
            return View(placeOrderModel);
        }

        [HttpPost]
        public ActionResult CancelCounterOrder(int order_id)
        {
            tbl_orders order = db.tbl_orders.Find(order_id);

            if(order == null)
            {
                return HttpNotFound();
            }

            order.order_status = "Cancelled";
            db.SaveChanges();

            return Json(new { success = true, message = "Order cancelled successfully." });
        }
    }
}

Views/ManagerCounterOrders/LoadManagerCounterOrders.cshtml
@model IEnumerable<Uling_RestaurantManagementSystem.Models.SQL.tbl_orders>

@{
    ViewBag.Title = "Counter Orders";
}

<div class="d-flex" id="wrapper">
    <!-- Sidebar-->
    @Html.Partial("_SideBar")

    <!-- Page content wrapper-->
    <div id="page-content-wrapper">
        <!-- Top navigation-->
        @Html.Partial("_Nav")

        <!-- Page content-->
        <div class="container-fluid">
            <div class="row px-5 pt-5">
                <div class="col-sm-12">
                    <p class="text-secondary" style="font-size: 1.5rem">Walk-In Orders</p>
                </div>
            </div>
            <!-- Navigation Tabs -->
            <ul class="nav nav-tabs mt-3" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <a class="nav-link active"
                       id="accepted-tab"
                       data-bs-toggle="tab"
                       href="#accepted-reservations"
                       role="tab"
                       aria-controls="accepted-reservations"
                       aria-selected="false">Accepted Orders</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link"
                       id="cancelled-tab"
                       data-bs-toggle="tab"
                       href="#cancelled-reservations"
                       role="tab"
                       aria-controls="cancelled-reservations"
                       aria-selected="false">Cancelled Orders</a>
                </li>
            </ul>


            <!-- Tab Content -->
            <div class="tab-content" id="myTabContent">
                <!-- ACCEPTED RESERVATIONS TAB -->
                <div class="tab-pane fade show active" id="accepted-reservations" role="tabpanel" aria-labelledby="accepted-tab">
                    <div class="row px-5">
                        <div class="col-sm-12">
                            <table class="table table-responsive table-light">
                                <thead>
                                    <tr>
                                        <th>Customer</th>
                                        <th>Total Amount</th>
                                        <th>Date Ordered</th>
                                        <th>Order Status</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null && !Model.Any())
                                    {
                                        <tr>
                                            <td colspan="7" class="text-center text-secondary">-- No take-out orders available --</td>
                                        </tr>
                                    }
                                    else
                                    {
                                        foreach (var order in Model.Where(w => w.order_status == "Accepted" || w.order_status == "Preparation" || w.order_status == "Ready"))
                                        {
                                            <tr>
                                                <td>@order.customer_name</td>
                                                <td>@order.total_amount</td>
                                                <td>@order.date_ordered.ToString("MMMM d, yyyy - h:mm tt")</td>
                                                <td>@order.order_status</td>
                                                <td>
                                                    <a href="@Url.Action("ViewOrderDetails", "ManagerCounterOrders", new { order_id = order.order_id })" class="text-decoration-none text-theme-1"><i class="fas fa-list-ul"></i></a>
                                                </td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <!-- CANCELLED RESERVATIONS TAB -->
                <div class="tab-pane fade" id="cancelled-reservations" role="tabpanel" aria-labelledby="cancelled-tab">
                    <div class="row px-5">
                        <div class="col-sm-12">
                            <table class="table table-responsive table-light">
                                <thead>
                                    <tr>
                                        <th>Customer</th>
                                        <th>Total Amount</th>
                                        <th>Date Ordered</th>
                                        <th>Order Status</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null && !Model.Any())
                                    {
                                        <tr>
                                            <td colspan="7" class="text-center text-secondary">-- No take-out orders available --</td>
                                        </tr>
                                    }
                                    else
                                    {
                                        foreach (var order in Model.Where(w => w.order_status == "Cancelled"))
                                        {
                                            <tr>
                                                <td>@order.customer_name</td>
                                                <td>@order.total_amount</td>
                                                <td>@order.date_ordered.ToString("MMMM d, yyyy - h:mm tt")</td>
                                                <td>@order.order_status</td>
                                                <td>
                                                    <a href="@Url.Action("ViewOrderDetails", "ManagerCounterOrders", new { order_id = order.order_id })" class="text-decoration-none text-theme-1"><i class="fas fa-list-ul"></i></a>
                                                </td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div> <!-- End of Tab Content -->
        </div>
    </div>
</div>

Views/ManagerCounterOrders/ViewOrderDetails.cshtml
@model Uling_RestaurantManagementSystem.Models.Custom.PlaceOrderModel
@using Uling_RestaurantManagementSystem.Utils.Functions

@{
    ViewBag.Title = "Order Details";

    Globals globals = new Globals();
}

<div class="d-flex" id="wrapper">
    <!-- Sidebar-->
    @Html.Partial("_SideBar")

    <!-- Page content wrapper-->
    <div id="page-content-wrapper">
        <!-- Top navigation-->
        @Html.Partial("_Nav")

        <!-- Page content-->
        <div class="container-fluid">
            <div class="row px-5 pt-5">
                <div class="col-sm-2"></div>
                <div class="col-sm-12">
                    <p class="text-secondary" style="font-size: 1.5rem">Order Details</p>
                </div>
            </div>

            <div class="row px-5">
                <div class="col-sm-4">
                    <dl class="row">
                        <dt class="col-sm-3 mt-1">Customer Name</dt>
                        <dd class="col-sm-9 mt-1">@Model.Order.customer_name</dd>

                        <dt class="col-sm-3">Contact No.</dt>
                        <dd class="col-sm-9">@Model.Order.contact_number</dd>

                        <dt class="col-sm-3">Email</dt>
                        <dd class="col-sm-9">@Model.Order.email</dd>

                        <dt class="col-sm-3">Total Amount</dt>
                        <dd class="col-sm-9">₱ @Model.Order.total_amount.ToString("F2")</dd>

                        <dt class="col-sm-3">Date Ordered</dt>
                        <dd class="col-sm-9">@Model.Order.date_ordered.ToString("MMMM d, yyyy - h:mm tt")</dd>

                        <dt class="col-sm-3">Order Status</dt>
                        <dd class="col-sm-9"><span class="badge rounded-pill @globals.GetTakeOutOrderBadgeClass(Model.Order.order_status)">@Model.Order.order_status</span></dd>
                    </dl>
                    @if (Model.Order.order_status != "Cancelled")
                    {
                        <form action="#" method="post" class="mt-5" id="cancelOrderForm">
                            <input type="hidden" name="order_id" id="input_order_id" value="@Model.Order.order_id" />
                            <button type="submit" class="btn btn-secondary">Cancel Order</button>
                        </form>
                    }
                </div>
                <div class="col-sm-6 bg-light py-4 px-5 rounded-corner">
                    <dl class="row mt-2">
                        <dt class="col-sm-4">Menu</dt>
                        <dt class="col-sm-3">Category</dt>
                        <dt class="col-sm-2">Quantity</dt>
                        <dt class="col-sm-3">Total</dt>
                    </dl>
                    <dl class="row" id="orderItemList">
                        @{
                            decimal subTotal = 0;
                            if (Model != null && !Model.OrderItems.Any())
                            {
                                <dd class="col-sm-12 text-secondary text-center">-- no orders --</dd>
                            }
                            else
                            {
                                foreach (var item in Model.OrderItems)
                                {
                                    subTotal += Convert.ToDecimal(item.line_price);

                                    string itemQuantity = item.quantity + "x";
                                    string linePrice = Convert.ToDecimal(item.line_price).ToString("F2");

                                    <dd class="col-sm-4">@item.tbl_menu_items.name</dd>
                                    <dd class="col-sm-3">@item.tbl_menu_items.category</dd>
                                    <dd class="col-sm-2">@itemQuantity </dd>
                                    <dd class="col-sm-3">₱ @linePrice</dd>
                                }
                            }
                        }
                    </dl>

                    <hr />
                    <dl class="row">
                        <dt class="col-sm-9 text-end">Subtotal: </dt>
                        <dd class="col-sm-3">
                            ₱ @subTotal.ToString("F2")
                        </dd>
                    </dl>
                </div>
                <div class="col-sm-2"></div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $('#cancelOrderForm').submit(function (e) {
            e.preventDefault();

            if ($('#input_order_id').val() == "") {
                alert("Unable to cancel order");
            }
            else {
                // jQuery object for the form
                var form = $(this);
                // Serialize the form data
                var formData = form.serialize();

                $.ajax({
                    url: '@Url.Action("CancelCounterOrder", "ManagerCounterOrders")',
                    type: 'POST',
                    data: formData,
                    success: function (response) {

                        const { success, message } = response;

                        if (success) {
                            form.trigger('reset');
                            alert(message);

                            var redirectUrl = '@Url.Action("LoadManagerCounterOrders", "ManagerCounterOrders")';
                            window.location.href = redirectUrl;
                        } else {
                            throw new Error("Something went wrong!")
                        }
                    },
                    error: function(xhr, status, error) {
                        alert('An error occurred: ' + error);
                    }
                });
            }
        })
    </script>
}